### ISSUE TITLE
dennis: planning end-of-life

### ISSUE THREAD

**Issue by willkg** [mozilla/vouched-mozillians#51]
I'm the current maintainer of [dennis](https://github.com/willkg/dennis). I'm maintaining too many things and I haven't used Dennis in years, so I'm looking at either:

1. passing maintenance to someone else
2. or, ending the project

Dennis is used in this project to lint PO files. If you're interested in taking over maintenance, that'd be great! If no one takes over, I'll shut down the project in May 2022.

Also, this repo seems like it's not active anymore. Should it get archived?

**Comment by akatsoulas** [comment]
This is a subset of the old mozillians.org to preserve vouches. Most probably this repo won't see any more development and even if it does I will be helping out maintaining dennis for SuMo.
